### ISSUE TITLE
ObjectMonitor no longer sending didUpdateObject: changedPersistentKeys:

### ISSUE THREAD

**Issue by PaulWoodIII** [JohnEstropia/CoreStore#12]
I'm on the xcode7 alpha branch and following you while you work, so I understand if you are going to get to it but my ObjectMonitor is no longer receiving this callback.

I looked into the NSFetchedResultsController used for the ObjectMonitor and instead of .Update its sending a .Move NSFetchedResultsChangeType. I think thats where I'll start in my debugging of this

**Comment by JohnEstropia** [comment]
I'm currently fighting with this as well, but this is not just a problem in the ios7_support_alpha branch. This also happens on any branch built with the iOS 9 SDK and *only on iOS 9 devices/simulators*, so it's either a bug on iOS 9, a bug on the latest XCode, or an inteded behavior change we may need to handle with `if #available()`'s.

**Comment by JohnEstropia** [comment]
Seems related: https://forums.developer.apple.com/thread/4999

**Comment by JohnEstropia** [comment]
@PaulWoodIII I pushed a **temporary** fix for ObjectMonitor so that it will somehow still be usable. A couple of problem still persists:

1. ObjectMonitor may send update events even if no updates actually occurred
2. ListMonitor may send willChange and didChange events even if no updates actually occurred. This will cause `UITableView.endUpdates()` to fire an assertion failure if no other UITableViewCell updates were made after `UITableView.beginUpdates()`.

We'll need to wait how Apple fixes this bug on the next XCode build. You can follow updates from this thread: https://forums.developer.apple.com/thread/4999

**Comment by PaulWoodIII** [comment]
thanks @JohnEstropia I'll test things out this afternoon myself
