### ISSUE TITLE
Add ability to pass persistent store options as parameter

### ISSUE THREAD

**Issue by sidlatau** [JohnEstropia/CoreStore#14]
I was unable to enable automatic migrations without modifying CoreStore code (to enable NSMigratePersistentStoresAutomaticallyOption and NSInferMappingModelAutomaticallyOption flags).

I added additional parameter to addSQLiteStoreAndWait method for passing options. 
```
    try dataStack.addSQLiteStoreAndWait(
        fileURL: sqliteFileURL, // set the target file URL for the sqlite file
        storeOptions: [NSSQLitePragmasOption: ["journal_mode": "WAL"], NSMigratePersistentStoresAutomaticallyOption: true, NSInferMappingModelAutomaticallyOption: true]
    )
```
Is there a better way to enable automatic migrations without this modification?

**Comment by JohnEstropia** [comment]
@sidlatau Thanks for the feedback!
The `DataStack` already sets `["journal_mode": "WAL"]` for you! If you search the code for **"journal_mode": "WAL"** you'll see that it's being set inside `addSQLiteStoreAndWait(...)`.

As for `NSMigratePersistentStoresAutomaticallyOption`, and `NSInferMappingModelAutomaticallyOption `, CoreStore is smart enough to do the same migration introspection without setting these flags. But, CoreStore does not allow migrations when you use `addSQLiteStoreAndWait(...)` because this is a blocking method and migrations may take time. To support migrations, you have to use the asynchronous methods of the form `addSQLiteStore(... completion:)` instead. 

It will help you a lot if you read the README on [migrations](https://github.com/JohnEstropia/CoreStore#migrations) for more details. Feel free to ask any other questions!
