### ISSUE TITLE
how to encrypted sql file by use corestore

### ISSUE THREAD

**Issue by yaochenfeng** [JohnEstropia/CoreStore#145]
how to encrypted sql file by use corestore

**Comment by JohnEstropia** [comment]
There is no built-in way to do this right now. Are you talking about Core Data's `NSPersistentStoreFileProtectionKey` option?

In the meantime, you can duplicate the code for `SQLiteStore` and implement your own `LocalStorage` that adds `NSPersistentStoreFileProtectionKey` option to the options dictionary:
```swift
class EncryptedSQLiteStore: LocalStorage, DefaultInitializableStore {
    // ...
    public let storeOptions: [AnyHashable: Any]? = [
        NSSQLitePragmasOption: ["journal_mode": "WAL"],
        NSPersistentStoreFileProtectionKey: NSFileProtectionComplete // add this
    ]
    // ...
}
```
Note that this just uses iOS's Data Protection API and the file is only encrypted when the user's device is passcode-locked.

Otherwise, if you are looking for a way to fully encrypt the database you would need to look for a separate framework, wrap it in an `NSIncrementalStore` implementation (I found [a very old library here](https://github.com/project-imas/encrypted-core-data/)), and then implement CoreStore's `LocalStorage` protocol. Needless to say, this seems like a lot of work.
