### ISSUE TITLE
Add OS X support on Cocoapods

### ISSUE THREAD

**Issue by iiiyu** [JohnEstropia/CoreStore#17]
I think CoreStore is a great third-party framework
I hope that on OS X programming also use pod install it
I tried to modify CoreStore of Cocoapods. But it depends on your other framework GCDKit.
GCDKit at Xcode7.0 have a [Bug](http://www.openradar.me/22437691). 
Cause I can not run to completion Unit Test
So I hope to get your help to make CoreStore support OS X, thank you.
@JohnEstropia

**Comment by JohnEstropia** [comment]
@iiiyu Thank you for your feedback!

Both CoreStore and GCDKit currently support only iOS just because I don't have OS X projects to test them with. Please feel free to make the necessary adjustments for OS X support, I'll be happy to accept pull requests!

As for the GCDKit bug (or rather, XCode 7's bug), I decided to just wait for XCode 7.1 (Swift 2.1) where I confirmed it was already fixed. I posted a workaround here: https://github.com/JohnEstropia/GCDKit/issues/6

**Comment by JohnEstropia** [comment]
@iiiyu I tried creating an OSX target but I have to disable `ListMonitor` and `ObjectMonitor` (for now?) because of their reliance on `NSFetchedResultsController` which OSX does not have. I'll spend a few more days to see if there's anything else that might break for OSX.

**Comment by iiiyu** [comment]
@JohnEstropia 
Oh, sorry. Until today saw your reply.

Ah now supports OS X biggest problem is that OS X does not NSFetchedResultsController. And ListMonitor and ObjectMonitor two classes CoreStore used inside a lot.

I think they actually provide functionality based NSFetchedResultsController may not be used in OS X inside.

Since I was Swift and OS X developers novice. Temporarily unable to provide support code on more

I'd be happy to help you test the OS X support

**Comment by JohnEstropia** [comment]
@iiiyu OSX support is out! Check out the latest pod version (1.3.3) or the master branch!

**Comment by iiiyu** [comment]
cool
