### ISSUE TITLE
perform(synchronous:) is not a rethrowing method as documented

### ISSUE THREAD

**Issue by sidmani** [JohnEstropia/CoreStore#188]
The documentation for `DataStack.perform(synchronous:)` states:  
 "Any errors thrown from inside the `task` will be rethrown from `perform(synchronous:)`".   
However, the signature is marked `throws`, not `rethrows`.  
`public func perform<T>(synchronous task: ((_ transaction: SynchronousDataTransaction) throws -> T), waitForAllObservers: Bool = true) throws -> T`  
Documentation error?

**Comment by JohnEstropia** [comment]
`perform(synchronous:)` just promises to "rethrow", that is to propagate, any errors you `throw` from inside the closure, not that it accepts non-throwing closures. It's explicitly `throws` because

1. The only way to cancel a transaction is to call `throw transaction.cancel()`
2. Declaring `rethrows` gives the illusion that non-throwing closures will never fail, which is not true (save errors may still be emitted)

**Comment by sidmani** [comment]
Gotcha, I think changing the word "rethrow" to "propagate" or something in the doc would make it clearer since rethrows is a keyword.

**Comment by JohnEstropia** [comment]
Thanks, I see the confusion. Will reword similar places in the documentations 👍
