### ISSUE TITLE
Issue with the experimental branch of swift 4

### ISSUE THREAD

**Issue by Plnda** [JohnEstropia/CoreStore#199]
/Users/pindakaasgroot/Development/Pinch/Telegraaf/Pods/CoreStore/Sources/DataStack+Migration.swift:650:25: Ambiguous use of 'withExtendedLifetime'

I get this error trying to compile with the experimental swift 4 branch

**Comment by JohnEstropia** [comment]
Are you using Cocoapods or Carthage?

**Comment by brosnic** [comment]
I have the same Issue. I'm using Cococapods

**Comment by Plnda** [comment]
@JohnEstropia Pods

**Comment by JohnEstropia** [comment]
Ah, this looks like the same problem as https://github.com/JohnEstropia/CoreStore/issues/184
Please make sure that your project is compiling CoreStore as Swift 4, not as Swift 3.2. (The reverse is also true if you're using the Swift3.2 branch)

Because Cocoapods doesn't have a per-pod Swift version setting yet, you can do this yourself from your Podfile:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'CoreStore'
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```
Or if you don't need the new stuff in the Swift4 branch yet, you can just use the Swift 3.2 branch instead. (to match your app's Swift version)

**Comment by JohnEstropia** [comment]
@Plnda @brosnic Did the SWIFT_VERSION configuration above help you?

**Comment by Plnda** [comment]
@JohnEstropia I got it working thanks!

**Comment by JohnEstropia** [comment]
Glad it's fixed. My recommendation is to use the corresponding Swift branch for your app's swift version:
Swift 3.2: `prototype/Swift_3_2`
Swift 4.0: `prototype/Swift_4_0`

**Comment by rsardek** [comment]
I have a freshly created app with SWIFT_VERSION = 4.0.
I cannot make any branch of CoreStore compile with it.

I have tried:
- pod 'CoreStore', '~> 4.0' ... which installs 4.2.0 and it leads Xcode showing broken CoreStore API changes;

- pod 'CoreStore', :git => 'https://github.com/JohnEstropia/CoreStore.git', :branch => 'prototype/Swift_4_0' .... which installs 5.0.0 and it leads to compiler throwing 
"fatal error encountered while reading from module 'CoreStore'.....DESERIALIZATION FAILURE ".

I tried the "per-pod Swift version setting" snippet suggested above, still no luck.

I am using Xcode 9.1 beta2.
