### ISSUE TITLE
Migration guide for MagicalRecord user?

### ISSUE THREAD

**Issue by sunkehappy** [JohnEstropia/CoreStore#212]
I'm a [MagicalRecord](https://github.com/magicalpanda/MagicalRecord) user. As we know it's been unmaintained for a long time. So I'm considering to switch a new library that is compatible with our existing code and that I could switch to step by step. It would be hard for me to remove MagicalRecord and add CoreStore in one step because it's highly coupled with my code.
So can anyone provide an migration guide for MagicalRecord user?

**Comment by JohnEstropia** [comment]
Hi, I'm not sure what we could consider a "migration guide", because you would need to rewrite everything. You can use your `xcdatamodeld` files and `NSManagedObject` as is, but other than those I'm afraid you'd need to reimplement most of your existing code. (CoreStore for example enforces transaction paradigms, and hides away `NSManagedObjectContext`s)

You can refer to the [README](https://github.com/JohnEstropia/CoreStore#contents) for how to implement common tasks.

**Comment by sunkehappy** [comment]
That would be very hard for users like me to transfer from MagicalRecord to this project because it would take a long time to rewrite everything. That's too risky. I should think twice before take any action.
