### ISSUE TITLE
Storing an array or dict with CoreStoreObject?

### ISSUE THREAD

**Issue by kevinrenskers** [JohnEstropia/CoreStore#215]
Is it possible to store an array or dict with CoreStoreObject? I noticed in another ticket that someone answered that question with one word: `Transformable`.

But something like this does not compile:

```
class Receipt: CoreStoreObject {
  let images = Transformable.Optional<[String]>("images")
}
```

![screen shot 2017-10-24 at 17 13 29](https://user-images.githubusercontent.com/229384/31965006-3c744656-b906-11e7-8ab3-6b1e90862b80.png)

Same goes for storing a `[String: Any]` dict, where I know all properties can be stored safely into Core Data (works great before refactoring to use CoreStoreObject). Any help would be greatly appreciated, thanks :)

**Comment by JohnEstropia** [comment]
`Transformer` currently only supports `NSCoding`. I've been planning to support Swift `Codable` types as well but haven't gotten around it yet, sorry. I wanted to provide a way to specify the encoder type (e.g. `JSONEncoder` or `PropertyListEncoder`), but some parts of `Transformable` may need rethinking because encoders don't have a common protocol, so we need to pass in an instance.

I'll bump this in my priority, in the meantime you can use `NSArray` and `NSDictionary`, which is what CoreData originally supports (through objc bridging). It might not have binary compatibility with the future `Codable` though.

**Comment by kevinrenskers** [comment]
Thanks works fine for now, thanks!

**Comment by bluepixeltech** [comment]
How do I CoreStoreObject class field with NSArray field?

**Comment by JohnEstropia** [comment]
@bluepixeltech I'm assuming you are using the `@Field` types now, in which case you can use `@Field.Coded` for codable arrays or dictionaries. See https://github.com/JohnEstropia/CoreStore#fieldcoded
