### ISSUE TITLE
ListMonitor refetch does not allow "Fetch Chain builders"

### ISSUE THREAD

**Issue by demonar** [JohnEstropia/CoreStore#242]
i'm updating the implementation on a project and found that when trying to update the old fashioned where, order, tweak clauses to the new form, i'm not allowed, but on the monitorList method i still can, this leaves a mix of styles in the code, if i were to parametrize some of the clauses to recall them i couldn't as they're not compatible, is there a way to add this in the future?

**Comment by JohnEstropia** [comment]
@demonar Hi, can you give more information on what you tried that didn't work?

**Comment by JohnEstropia** [comment]
It's been many months and I apologize that this issue got buried. Looking back into `refetch()`, it's not really compatible with fetch builders because of it's special nature:
1. It replaces only the `FetchClause` that you specify, which means it keeps the old clauses for those you didn't specify
2. It only accepts `Where`, `OrderBy`, and `Tweak` clauses.

Due to these the current `refetch()` API being "old fashioned" is by design.
