### ISSUE TITLE
Demo Project : Missing Dependency

### ISSUE THREAD

**Issue by wm-j-ray** [JohnEstropia/CoreStore#26]
John,

I got a 'Missing dependency target GCDKit. error when trying to run your example.  Just a heads up.  

I dragged and dropped in the original source of GCDKit project to get up and running.  Tried to run the demo under xCode 7.1.1, IOS 9.1.  She builds, LaunchScreen.xib comes up and the demo crashes.  I have the simulator location set to 'Apple.'

Fixed it.

OK, this what I did (I hate cocoa pods).  So I don't use it and prefer Carthage.  I commented out the 

    //#if USE_FRAMEWORKS
        import GCDKit
    #endif

in CoreStore.swift and the demo runs

**Comment by JohnEstropia** [comment]
@wm-j-ray Thanks for the feedback! The demo app builds CoreStore as a framework, which means that GCDKit should also be built as a framework. If you just dragged and dropped the source then it won't be built as a framework, which is why commenting out the `import` statement makes it work for you.

You can clone CoreStore including GCDKit using
```
git clone --recursive https://github.com/JohnEstropia/CoreStore.git
```

I'm pretty sure Carthage should manage submodules for you though so I'm not sure why GCDKit was not in your folder in the first place..

**Comment by wm-j-ray** [comment]
Thanks for the help.

**Comment by JohnEstropia** [comment]
I'll close this for now but feel free to reopen the issue if you still have other problems.
You can also try the workaround discussed here https://github.com/JohnEstropia/CoreStore/issues/27
