### ISSUE TITLE
Problem with early-deallocated fetched objects

### ISSUE THREAD

**Issue by clouddevil** [JohnEstropia/CoreStore#290]
I have a problem with early-deallocated fetched objects.

Please, can you see what is wrong?

https://github.com/clouddevil/CoreStore/blob/6859babd5c63b5dcd9d18034291d174db681c105/CoreStoreTests/IssueTests.swift#L53

and some tests for legacy storage are broken.

**Comment by JohnEstropia** [comment]
You will never get the same store if you use the `BaseTestCase. prepareStack()` method because it generates a new UUID (thus a new sqlite file) for each call.
See: https://github.com/JohnEstropia/CoreStore/blob/develop/CoreStoreTests/BaseTests/BaseTestCase.swift#L53

If you wish to use a shared store just call `addStorage()` on your own.

**Comment by clouddevil** [comment]
Oh YES!  thank you!!
