### ISSUE TITLE
Swift 2.0 support

### ISSUE THREAD

**Issue by ejensen** [JohnEstropia/CoreStore#3]
I'm starting a new project with Swift 2.0 and would like to use CoreStore. Is Swift 2.0 support on the roadmap?

**Comment by JohnEstropia** [comment]
Yes! In fact I have a Swift 2.0-converted repository locally, but I haven't pushed it yet.
The reason is I'm planning to rewrite the error-handling to use `throw`ing methods instead of the current `enum`-returning methods.

I can't say how long it would take though; I'm also writing migration utilities right now (prototype in the *develop* branch).

**Comment by pagliara** [comment]
CoreStore has been really useful in a project I'm working on now.  Support for Swift 2.0 would be greatly appreciated.

**Comment by JohnEstropia** [comment]
@ejensen @pagliara 
I have pushed the Swift 2.0-converted version (along with migration utilities) to the develop branch. The error handling will undergo a big overhaul so a rewrite will be required later on, but you should be able to build projects in Swift 2.0 with the current develop branch.
