### ISSUE TITLE
CoreStore with Cocoapods and Firebase

### ISSUE THREAD

**Issue by viatsyshyn** [JohnEstropia/CoreStore#305]
Hello, I was using CoreStore in my app installed via Cocoapods frameworks mode. Now I need to have Firebase also in project, but it's incomatible with frameworks mode. When I switch off frameworks, re install pods and build app, I get CoreStore compilation errors. Mostly like 

```
Type 'NSManagedObject' does not conform to protocol 'DynamicObject'
```

Does CoreStore thru CocoaPods work only in frameworks mode ?

**Comment by JohnEstropia** [comment]
Not sure about the issue here. I have a project that uses `use_frameworks!` in the Podfile and with both Firebase and CoreStore dependencies.

As for CocoaPods' static framework support, I'm not sure most open source libraries work properly on this mode. Have you tried `pod 'CoreStore', :modular_headers => true` in your Podfile?

**Comment by JohnEstropia** [comment]
After a quick google of the issue this looks like a common React Native issue:
https://github.com/react-native-community/react-native-maps/issues/2218

Someone has posted a solution here using [cocoapods-fix-react-native](https://github.com/orta/cocoapods-fix-react-native) so you may want to look at that: 
https://github.com/react-native-community/react-native-maps/issues/2324

**Comment by viatsyshyn** [comment]
Hi, ended up, including RN plugin directly into xcode project, same way as for AirMaps (react-native-maps).
