### ISSUE TITLE
fetchLimit is not working with ListPublisher

### ISSUE THREAD

**Issue by EricSKCheng** [JohnEstropia/CoreStore#350]
First I create a ListPublisher
```
CoreStoreDefaults.dataStack.publishList(From<Article>()
            .orderBy(.descending(\.publishDate))
            .tweak { $0.fetchLimit = 10 })
```

and add a addObserver
```
addObserver(self) { [weak self] (listPublisher) in
            
        }
```
however if I add a new article to the corestore, the observer will return more than 10 items.

**Comment by JohnEstropia** [comment]
This is a limitation of `NSFetchedResultsController` which also affects `ListMonitor`.

Fortunately, `ListPublisher`s use diffing instead of relying on FRC update methods, so we can easily simulate the fetch limit by hand.(i.e. just truncate the unwanted items from the snapshot)

I'll post an update soon.

**Comment by EricSKCheng** [comment]
Thx.

**Comment by JohnEstropia** [comment]
Implemented in `develop` branch 👍
