### ISSUE TITLE
Xcode 7.3, branch iOS 7 doesn't compile 

### ISSUE THREAD

**Issue by JustaLab** [JohnEstropia/CoreStore#56]
With the latest version of Xcode and Swift 2.3, the library doesn't compile anymore.  I get  "Ambiguous use of init" whenever i use the From, for instance:
`transaction.deleteAll(From(CDNotification))`

Just saw that a similar error has been fixed on the develop branch, will you consider fixing it on the iOS 7 as well?

**Comment by JohnEstropia** [comment]
@JustaLab Yup, I haven't updated the iOS 7 branch for XCode 7.3 yet. Let me make a fix within the day

**Comment by JohnEstropia** [comment]
@JustaLab The master and develop branches now both support iOS 7. Check out the **CoreStore iOS7** XCode scheme. Tell me if you have any issues.

BTW, I'll be deleting the **ios_support_alpha** branch in the near future so please update when you can.

**Comment by JustaLab** [comment]
@JohnEstropia Awesome thanks for your time! I've switch to latest tag. It looks like it's all working fine with iOS 7. Do you plan on making it available with CocoaPods?

**Comment by JohnEstropia** [comment]
Great, thanks for confirming! I'll push the podspec then later in the day.

**Comment by JohnEstropia** [comment]
Oh right, I remember now. The latest 1.6.1 tag already supports iOS 7 but I cannot change the pod min version to iOS 7 because dynamic frameworks do not work in iOS 7. 

Since Swift files can only be distributed through CocoaPods using frameworks, I suggest you try Carthage or git submodules instead. But even then, you still cannot link the "CoreStore iOS7" scheme to your project, you need to include the .swift files directly to your App's build target.

This is true for both CoreStore and GCDKit. I'll update the README to make this clearer.

**Comment by JustaLab** [comment]
OK, no problem, I added it as a submodule indeed.
Thanks!
