### ISSUE TITLE
How can I make update with mainContext?

### ISSUE THREAD

**Issue by Koshub** [JohnEstropia/CoreStore#62]
Due the CoreData cache sometimes I have to call `refreshAndMerge` to refetch objects from persistaten store. Do we have an API to update objects directly with main context, not with child of main?

**Comment by JohnEstropia** [comment]
CoreStore's main context is strictly readonly. This was designed for performance and integrity.

I suggest you use ListMonitor or ObjectMonitor; objects managed by NSFetchedResultsController automatically gets refreshed.

**Comment by Koshub** [comment]
Not sure your suggestion will resolve the issue. For example, I update `Project` entity and then after that immediately I try to load entity (`FeedItem`) with one-to-one relation of that `Project` and I receive unupdated object. Here is my code with comments where I have to put refresh calls:
```swift
    func updateProject(project: Project) {
        CoreStore.beginSynchronous { (transaction) -> Void in
            if let projectModel = transaction.fetchOne(From(CDProject), Where("identifier == %@", project.identifier)) {
                projectModel.updateWithProject(project)
            }
            transaction.commitAndWait()
        }
    }

    func feedItemWithId(id: String) -> FeedItem? {
        if let feedItemModel = CoreStore.fetchOne(From(CDFeedItem), Where("identifier == %@", id)) {
            // Need to call here feedItemModel.refreshAndMerge()
            var item = FeedItemMapper.fromCDFeedItem(feedItemModel)
            if let projectModel = feedItemModel.project {
                // Need to call here projectModel.refreshAndMerge()
                item.project = ProjectMapper.fromCDProject(project: projectModel)
            }
            return item
        } else {
            return nil
        }
    }

```

**Comment by JohnEstropia** [comment]
This behaviour is `NSManagedObject`'s caching mechanism and beyond CoreStore's control
(and thus the existence of `refreshAndMerge()` and `refreshAsFault()` methods.)

Like I mentioned, `NSFetchedResultsController` does this for free, but with the cost of constantly processing its objects. Otherwise, calling `refreshAndMerge()` like how you did is correct.

For the record, we can extend CoreStore to do this automatically all the time, but the performance cost may not be worth it.

**Comment by Koshub** [comment]
Thank you for response. I can't user `NSFetchedResultsController`. I think if I have the API to update objects with main context, not child, I will fetch always correct objects. I understand that you need child context to implement amazing transactions logic. Also I understand that I can use main context through  fetched managed objects. Although I think you have the other reasons to make main context readonly I will be very happy if you try to provide some API to interact directly with main context. Thank you for your time and excellent Pod library.

**Comment by JohnEstropia** [comment]
Allowing updates to the main context objects means two things:
1. You are bypass all transactions, which breaks the deterministic order of updates.
2. You introduce a "non-saved" state in the main context. This is bad because 1) the main context's children (i.e. in transactions) will see a different snapshot of objects, and 2) you may be showing the User something that is not actually in the disk file yet.
3. CoreData's processing gets loaded to the main queue (which is the main context's queue). This introduces UI lags and the risk of deadlock.

So sorry, I prefer the main context the way it is. IMO it's a small price to pay for all the safety and guarantees that CoreStore offers.

**Comment by Koshub** [comment]
I see. I understand all these things. You are right. Thank you.
