### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by tosbaha** [JohnEstropia/CoreStore#82]
Hi,
Thanks for such a great library. I am in the middle of upgrading my Core Data layer and I was searching for library and luckily I found yours. I think your library by far has the best documentation. I forked and tried to upgrade to Swift 3 syntax but after 20 minutes I still couldn't make it build. I will really appreciate if you can create Swift3 branch so that people like me can have more time to test it out before Swift 3 becomes stable. Best regards.

**Comment by JohnEstropia** [comment]
Thanks for the feedback!
I'm working on the Swift 3 conversion right now. It's taking a while because I want to meet the Swift 3 API Design Guideline, but the Swift 3 branch should be ready within a couple weeks :)

**Comment by JohnEstropia** [comment]
To everyone watching this thread, a working library is in the [swift3_develop](https://github.com/JohnEstropia/CoreStore/tree/swift3_develop) branch.

Do note that due to Swift 3 not yet in it's final stage and me still not satisfied of the Swift-3-ness of some of CoreStore's API naming rules, there's a good chance that it will be refactored once or twice more before the final Swift 3 release.

**Comment by JoeMatt** [comment]
Now that Swift 3 has many (all?) of the GCD features of GCD kit (with almost the same syntax, they must have been inspired) will that library be dropped in favor of the Swift 3 APIs?

How does the introduction of CoreData generations effect CoreStore? Will the new APIs for syncing and such be exposed? Is concurrency less of an issue, it seems they're making it just work?

**Comment by JohnEstropia** [comment]
> GCDKit
Yup, I wanted to try migrating to the new dispatch API but the last beta broke my local build so I thought just wait for the final version of the API before I fully commit.

> iOS 10 Core Data
I have no iOS 10 device yet so I haven't tried, but I heard the new SDK changes should "just work". Now knowing iOS SDK updates I doubt that's true, but I'm holding off any actual testing until after Swift 3 is sorted out and the iOS 10 GM build is released.

**Comment by JohnEstropia** [comment]
Just to update, the `swift3_develop` branch is fully working right now.
GCDKit dependency was also removed and the demo app works fine on iOS 10.

That said, I encourage everyone to wait for the final `master` version because I am still updating the API to match the Swift 3 API Guidelines. If anyone wants to suggest improvements regarding Swift 3, feel free to comment or make pull requests!

**Comment by mrichtsfeld** [comment]
Hi @JohnEstropia 

Great framework, love working with it. I have been using with with swift3 now for almost 2 months and it works fine. Do you plan to merge it to master soon?

Thanks

**Comment by JohnEstropia** [comment]
@mrichtsfeld Yes it does work fine :) We use it in our apps as well. I just have a couple more pending refactors before I can finalize the Swift 3 branch.

**Comment by mrichtsfeld** [comment]
@JohnEstropia Looking forward to it. Thanks for the update.

**Comment by innoreq** [comment]
Hi @JohnEstropia,

great lib - any news on Swift3 migration? Or at least some indication about when it will be available?

**Comment by JohnEstropia** [comment]
Sorry for the long wait, Swift 3 is now in the master branch and pushed to Cocoapods as version 3.0.0!
